name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Mutation Test
      run: dotnet stryker -tp /home/runner/work/mutation-testing-csharp/mutation-testing-csharp/Mutation.Foo.Tests/Mutation.Foo.Tests.csproj -tr DotnetTest
